### ISSUE TITLE
RenderStepped Event cause SEGFAULT

### ISSUE THREAD

**Issue by DigiTechs** [JohnMHarrisJr/OpenBlox#6]
Simply connecting a RenderStepped event with no body causes a SEGFAULT later on in the program execution.

**Comment by JohnMHarrisJr** [comment]
This is interesting.

**Comment by JohnMHarrisJr** [comment]
Where is RenderStepped being fired in our code?

**Comment by JohnMHarrisJr** [comment]
I'm looking into this, a possible solution is a complete rewrite of the task scheduler.

**Comment by JohnMHarrisJr** [comment]
Support for the previous version of OpenBlox has been dropped. If this bug persists into the rewrite of OpenBlox this may be re-opened.
